### ISSUE TITLE
Hang on start.

### ISSUE THREAD

**Issue by SaikoHaven** [NatTupper/dline#18]
Hi. I am getting this when starting dline..
```
Checking for updates...
Already up to date!

Starting...
```
then it hangs.. Can I get some help with this?

**Comment by NatTupper** [comment]
Sure. Sorry for the wait. The project has been on the backburner for quite some time now.

Please edit your config file located at ~/.config/dline/config.yaml and change `debug` to `true`. Re-run dline and do not close it. Post the output of `debug.log` here. Once you do, you may kill the program.

**Comment by NatTupper** [comment]
Any update?

**Comment by Nevexo** [comment]
From what I've found, on my main account (that has guilds with none-ASCII characters) I get a crash with this trace:

`
INFO:root:Ignoring exception in on_ready
ERROR:root:Traceback (most recent call last):

ERROR:root:
ERROR:root:  File "/root/.local/lib/python3.6/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)

ERROR:root:
ERROR:root:  File "/root/dline/dline/__main__.py", line 92, in on_ready
    gc.client.set_current_guild(gc.settings["default_guild"])

ERROR:root:
ERROR:root:  File "/root/dline/dline/client/client.py", line 108, in set_current_guild
    if guild.lower() in gld.name.lower():

ERROR:root:
ERROR:root:AttributeError: 'NoneType' object has no attribute 'lower'
`

But on an alt account with no fancy characters in guild names (why the hell do people have to do that) it works just fine.
